version: '3.3'
 
services:
  slim:
    container_name: event-sourcing
    volumes:
      - "./:/var/www"
    build: .
    command: ["php", "-S", "0.0.0.0:8080"]
    ports:
      - "80:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
